name: Publish

on:
    push:
        tags: ['v*']

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-node@v4
              with:
                  node-version-file: .nvmrc
                  cache: npm

            - run: npm ci
            - run: npm run verify
            - run: npm run build

            - name: Compute version
              id: version
              run: echo "version=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT

            - name: Publish
              env:
                  NPM_REGISTRY_TOKEN: ${{ secrets.NPM_REGISTRY_TOKEN }}
                  RELEASE_TAG: ${{ steps.version.outputs.version }}
              run: |
                  echo "//nexus.sector.sh/repository/yarn-empg/:_auth=${NPM_REGISTRY_TOKEN}" >> .npmrc
                  npm version --allow-same-version --no-git-tag-version ${RELEASE_TAG}
                  npm publish
